#!/usr/bin/env python3
"""Build a multi-file ("bundle") package for pkg.

  tools/mkbundle.py packages/NAME            builds pkgs/NAME/ and updates journals/main.journal
  BASE_URL=https://host/path tools/mkbundle.py packages/NAME     (default: this repo's raw.githubusercontent.com URL)

packages/NAME/bundle.spec lines (see packages/wtms/bundle.spec):
  name NAME | version V | abi N | program SRC.c -> DEST [flags=-DX name=FILE.aot] | file SRC -> DEST | copy SRC_DEST DEST | dir PATH | service NAME | note TEXT
Output: pkgs/NAME/<files> and pkgs/NAME/MANIFEST (what `pkg install NAME` downloads first), plus the journal line
  bundle NAME VERSION <manifest url> sha256=... size=... abi=N
"""
import hashlib, os, re, shutil, subprocess, sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
pkgdir = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else sys.exit(__doc__))
base = os.environ.get('BASE_URL', 'https://raw.githubusercontent.com/hamimmahmud0/miniesp/main/pkgs').rstrip('/')

meta, ops = {}, []
for line in open(os.path.join(pkgdir, 'bundle.spec')):
    line = line.rstrip('\n')
    if not line.strip() or line.lstrip().startswith('#'):
        continue
    k, _, rest = line.partition(' ')
    if k in ('name', 'version', 'abi'):
        meta[k] = rest.strip()
    else:
        ops.append((k, rest.strip()))
name = meta['name']
out = os.path.join(root, 'pkgs', name)
shutil.rmtree(out, ignore_errors=True)
os.makedirs(out)

def sha(path):
    return hashlib.sha256(open(path, 'rb').read()).hexdigest()

manifest = ['# %s %s (bundle). Generated by tools/mkbundle.py: do not edit.' % (name, meta['version'])]
notes = []
for k, rest in ops:
    if k in ('program', 'file'):
        src, _, dest = [x.strip() for x in rest.partition('->')]
        src = os.path.normpath(os.path.join(pkgdir, src))
        opts = dict(t.split('=', 1) for t in dest.split()[1:] if '=' in t)     # optional: flags=-DX  name=FILE.aot
        dest = dest.split()[0]
        fname = opts.get('name', os.path.basename(dest))
        target = os.path.join(out, fname)
        if k == 'program':
            tmp = os.path.join(out, '.build')
            os.makedirs(tmp, exist_ok=True)
            subprocess.run(['./build.sh', os.path.basename(src)], cwd=os.path.dirname(src),
                           env=dict(os.environ, OUT=tmp, CFLAGS_EXTRA=opts.get('flags', '')), check=True, stdout=subprocess.DEVNULL)
            os.replace(os.path.join(tmp, os.path.splitext(os.path.basename(src))[0] + '.aot'), target)
            shutil.rmtree(tmp, ignore_errors=True)
        else:
            shutil.copy(src, target)
        manifest.append('file %s %s/%s/%s sha256=%s size=%d' % (dest, base, name, fname, sha(target), os.path.getsize(target)))
    elif k == 'copy':
        manifest.append('copy ' + rest)
    elif k in ('dir', 'service'):
        manifest.append('%s %s' % (k, rest))
    elif k == 'note':
        notes.append('note ' + rest)
    else:
        sys.exit('bundle.spec: unknown keyword ' + k)
manifest += notes
mpath = os.path.join(out, 'MANIFEST')
open(mpath, 'w').write('\n'.join(manifest) + '\n')
entry = 'bundle %s %s %s/%s/MANIFEST sha256=%s size=%d abi=%s' % (name, meta['version'], base, name, sha(mpath), os.path.getsize(mpath), meta['abi'])

jpath = os.path.join(root, 'journals', 'main.journal')
lines = [l for l in open(jpath).read().split('\n') if not re.match(r'bundle %s ' % re.escape(name), l)]
while lines and lines[-1] == '':
    lines.pop()
lines.append(entry)
open(jpath, 'w').write('\n'.join(lines) + '\n')
print('built pkgs/%s/ (%d files); journal updated:' % (name, len(os.listdir(out)) - 1))
print(entry)
